### ISSUE TITLE
Shall we get a Custom Domain for the GitHub Pages?

### ISSUE THREAD

**Issue by trembl** [BioClub/BHA5#8]
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

If yes, which Domain Name?

- bha5.bioclub.org
- biohackacademy . jp? .tokyo? .io? .bio?

_Any other suggestions?_

**Comment by sotakan** [comment]
bhatokyo.xyz is available too

**Comment by trembl** [comment]
I have bioclub.tokyo. We can use bha.bioclub.tokyo - or bha.bioclub.org

**Comment by sotakan** [comment]
If you want mail, point MX records to mx.sotakan.com

**Comment by trembl** [comment]
I pointed the GitHub Pages to bha5.bioclub.tokyo for now. Pages are served from /docs. Next steps: Style & Content
